# Trufflehog Scan
# Scan the last 50 commits in a repository for secrets
# https://github.com/edplato/trufflehog-actions-scan

name: Trufflehog Scan
on: [push]

jobs:
  scanSecrets:
    name: Trufflehog Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=False --rules /regexes.json"
